Add segy->npy code and new test SEG-Y files
olgaliak/seismic-deeplearning pull request #11
Opened 2020-02-06 17:52 UTC by MJZawacki

I'm still updating the README but want to get this out for an early review.

* Update segy files used by unit testing
* Remove dependency on Blob storage - We can later add it in a pipeline to run on multiple files
* Add notebook to create test data and describe issues with segy files
* Add notebook showing how to run the conversion script
* Rename script to convert_segy.py

close #1 
close #3 

TODO:
@olgaliak @GeisaFaustino I have added a flag to turn on normalization but based on yesterday's conversation, I think we also need a flag to turn on clipping. So the script can normalize&clip, just clip, or leave the data as is. Thoughts?

2020-02-07 16:23 UTC, olgaliak approved these changes

2020-02-11 16:12 UTC, maxkazmsft requested changes
Could you please issue into "contrib" branch of the root repo?

2020-02-13 14:21 UTC, GeisaFaustino commented on contrib/segyconverter/test/test_normalizecube.py
> +# pylint: disable=import-error
I thought this file had been renamed to test_dataprep.py.  No?

2020-02-13 14:22 UTC, GeisaFaustino commented on contrib/segyconverter/utils/normalize_cube.py
> +# pylint: disable=import-error
The same here. This file was renamed to dataprep.py...

2020-03-02 18:11 UTC, closed without merging